django/config/urls.py
from django.contrib import admin
from django.urls import path, include

import core.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core'))
]

django/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies', views.MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail')
]

django/core/models.py
from django.db import models


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),
    )

    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)

    director = models.ForeignKey(to='Person', on_delete=models.SET_NULL, related_name='directed', null=True, blank=True)
    writers = models.ManyToManyField(to='Person', related_name='writing_credits', blank=True)
    actors = models.ManyToManyField(to='Person', through='Role', related_name='acting_credits', blank=True)

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({} - {})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died,
            )
        return '{}, {} ({})'.format(
            self.last_name,
            self.first_name,
            self.born,
        )


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    class Meta:
        unique_together = ('movie', 'person', 'name')

    def __str__(self):
        return '{} {} {}'.format(self.movie_id, self.person_id, self.name)

django/core/views.py
from django.views.generic import ListView, DetailView

from .models import Movie


class MovieList(ListView):
    model = Movie
    paginate_by = 10


class MovieDetail(DetailView):
    model = Movie

django/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ object.title }} - {{ block.super }}
{% endblock title %}

{% block main %}
  <h1>{{ object }}</h1>
  <p class="lead">
    {{ object.plot }}
  </p>
{% endblock main %}

{% block sidebar %}
  <div>
    This movie is rated:
    <span class="badge badge-primary">
        {{ object.get_rating_display }}
      </span>
  </div>
{% endblock sidebar %}

django/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
  All the Movies
{% endblock title %}

{% block main %}
  <ul>
    {% for movie in object_list %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
          {{ movie }}
        </a>
      </li>
    {% endfor %}
  </ul>
  {% if is_paginated %}
    <nav>
      <ul class="pagination">
        <li class="page-item">
          <a href="{% url 'core:MovieList' %}?page=1" class="page-link">
            First
          </a>
        </li>
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}" class="page-link">
              {{ page_obj.previous_page_number }}
            </a>
          </li>
        {% endif %}
        <li class="page-item active">
          <a href="{% url 'core:MovieList' %}?page={{ page_obj.number }}" class="page-link">
            {{ page_obj.number }}
          </a>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}" class="page-link">
              {{ page_obj.next_page_number }}
            </a>
          </li>
        {% endif %}
        <li class="page-item">
          <a href="{% url 'core:MovieList' %}?page=last" class="page-link">
            Last
          </a>
        </li>
      </ul>
    </nav>
  {% endif %}
{% endblock main %}

django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
  <title>
    {% block title %}
      MyMDB
    {% endblock title %}
  </title>
  <style>
    .mymdb-masthead {
      background-color: #EEE;
      margin-bottom: 1em;
    }
  </style>
</head>
<body>
<div class="mymdb-masthead">
  <div class="container">
    <nav class="nav">
      <div class="navbar-brand">MyMDB</div>
      <a href="{% url 'core:MovieList' %}" class="nav-link">
        Movies
      </a>
    </nav>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-8 mymdb-main">
      {% block main %}{% endblock main %}
    </div>
    <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
      {% block sidebar %}{% endblock sidebar %}
    </div>
  </div>
</div>
</body>
</html>